# Password that Crowd Control clients must enter to connect to this Crowd Control server.
# This may be temporarily overridden using the "/password" command.
password: "crowdcontrol"

# The port to listen for incoming connections on.
# This port must be opened in your system's (or router's) firewall.
port: 58431

# Makes it so that all purchased effects apply to everyone on the server,
#  even when running in server-mode with individually connected clients.
global: false

# The hosts or owners of a server, through which viewers are able to purchase specific universal
#  effects such as setting the server difficulty or changing the weather.
# Acceptable values for this field include Minecraft usernames,
#  UUIDs (formatted with or without dashes), stream usernames, and stream IDs.
# Example:
#hosts: ["MinecraftUsername1", "TwitchUsername2", "123456", "d1de9ca878f64aae87a18c112f675f12"]
hosts: []

# Determines whether to alert streamers in chat when an effect has been activated.
announce: true

# Determines whether a user must be an operator to use the "/account" command.
admin-required: false

# When the server fails to find a player that matches data sent by the Crowd Control app for the purposes of
# auto-linking Minecraft and Crowd Control accounts, this setting allows a fallback to find a matching Minecraft player
# using connected IP addresses. This may be undesirable for some event setups.
ip-detect: true

# Hides the names of viewers who have purchased effects.
# Can be 'none' to disable, 'chat' to hide only in chat, or 'all' to hide everywhere.
hide-names: none

# Limits the number of players who can be affected by a purchased effect.
# For example, if a viewer redeems Give End Portal Frame and the limit is set to 1, then only
#  one random player will receive an end portal frame.
# Players listed in the "hosts" field are prioritized over guests.
# A value of 0 will disable that limit. If you instead wish to disable an effect entirely then you
#  may do so in the Crowd Control app's pricing menu.
limits:

  # Whether hosts should bypass limits entirely.
  hosts-bypass: true

  # Limits for giving items.
  items:
    default: 0
    end_portal_frame: 1

  # Limits for spawning entities.
  entities:
    default: 0
    ender_dragon: 1
    wither: 1

##################
# Legacy Options #
##################

# When enabled, the plugin will run using the legacy client mode.
# This mode is considered legacy as it is unsupported by the Crowd Control app.
# You will need a custom .ccpak file to use this mode.
legacy: false

# IP address to connect to when running in the legacy client mode.
# This should usually be a local IP address (i.e. "127.0.0.1") unless this server is being
#  run on a different machine than the streamer's PC.
# This value is not applicable when running in server mode and thus will be ignored.
ip: 127.0.0.1
