# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16', '17' ]
    name: Build on Java ${{ matrix.Java }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

      - name: Upload Paper Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crowdcontrol-paper
          path: "paper/build/libs/CrowdControl-*.jar"

      - name: Upload Sponge 7 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crowdcontrol-sponge7
          path: "sponge-7/build/libs/CrowdControl-*.jar"

      - name: Upload Sponge 8 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crowdcontrol-sponge8
          path: "sponge-8/build/libs/CrowdControl-*.jar"

      - name: Upload Fabric Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crowdcontrol-fabric
          path: "fabric/build/libs/CrowdControl-*.jar"
